// Lista de funcoes permitidas no formulario publico de cadastro de equipe.
// Usada para validacao no submit e exibicao no formulario frontend.
export const JOB_ROLES = [
  'Diretor de Cena',
  'Roteirista',
  'Atendimento',
  'Produtor(a) de Locação',
  'Diretor de Produção',
  'Coordenador de Produção',
  'Produtor',
  'Assistente de Produção I',
  'Assistente de Produção II',
  'Assistente de Produção III',
  'Assistente de Produção IV',
  'Produtor de Casting',
  'Produtor de Locação',
  'Diretor de Arte',
  'Assistente de Arte',
  'Ajudante de Arte I',
  'Ajudante de Arte II',
  'Pesquisa e Layouts',
  'Produtor de Objetos',
  'Assistente de Objetos',
  'Contra Regra',
  'Assistente de Contra Regra',
  'Retirada de Arte',
  'Devolução de Arte',
  'Efeitista',
  'Produtor de Figurino',
  'Assistente de Figurino I',
  'Assistente de Figurino II',
  'Camareira',
  'Maquiador(a)',
  'Assistente de Maquiagem',
  'Cabelereiro(a)',
  'Make/Hair',
  'Assistente de Make',
  'Assistente de Direção I',
  'Assistente de Direção II',
  'Logger / Script Supervisor',
  'Diretor de Fotografia',
  'Operador de Câmera',
  'Assistente de Câmera I',
  'Assistente de Câmera II',
  'DIT',
  'Video Assist',
  'Making Of',
  'Chefe de Elétrica (Gaffer)',
  'Assistente de Elétrica I',
  'Assistente de Elétrica II',
  'Chefe de Maquinária',
  'Assistente de Maquinária I',
  'Assistente de Maquinária II',
  'Operador de Ronin / Steadicam',
  'Operador de Drone',
  'Técnico de Som Direto',
  'Microfonista',
  'Assistente de Som',
  'Motorista',
  'Fotógrafo Still',
  'Assistente de Fotógrafo',
  'Coordenador de Pós',
  'Editor de Vídeo',
  'Finalizador / VFX',
  'Motion Designer',
  'Colorista',
  'Designer Gráfico',
  'Técnico de Áudio',
  'Responsável por Condecine',
  'Advogado',
  'Geradorista',
  'Outros',
] as const

export type JobRole = typeof JOB_ROLES[number]
