-- bank_accounts migration: equipe
-- Generated by parse_custos_csv.py

INSERT INTO bank_accounts (tenant_id, vendor_id, bank_name, pix_key, pix_key_type)
VALUES
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('José Warlen Alves Brito')) LIMIT 1), 'Itau', '44773116000139', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Rosivaldo jesus de almeida')) LIMIT 1), 'Banco Itaú  Empresa', 'Ele E Maq Filmagens Lta Me', 'aleatoria'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Raul Martins Bittencourt')) LIMIT 1), '206', '52621210000109', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Erika Souza')) LIMIT 1), 'BRADESCO - CASA DO PRODUTOR CINE E EVENTOS', '28277865000119', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Gesiel Muniz de Carvalho')) LIMIT 1), 'ITAÚ', '11997110466', 'cpf'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Tatiane de Oliveira Gomes')) LIMIT 1), 'C6', '34315644000190', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Diego Gaeta')) LIMIT 1), 'Mercado Pago', '31483783855', 'cpf'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Fullcine')) LIMIT 1), 'Itaú Unibanco', '02513238000227', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Heverton Edberg Souza Gil da Silva /HES CATERING E EVENTOS')) LIMIT 1), 'itau', 'cafemaniakatiagil@gmail.com', 'email'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Marcos paulo saraiva')) LIMIT 1), 'Santander', '11988266039', 'cpf'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Edwilson Damião Guedes')) LIMIT 1), 'Inter', '31698454000101', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('TRANSKINDERR LOCADORA DE VEÍCULOS')) LIMIT 1), '237 - BRADESCO', '07163326000189', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Claudenice do Nascimento Vilas Boas')) LIMIT 1), 'Itau', '11999486014', 'cpf'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Maurício Lopes fontoura')) LIMIT 1), 'Picpay', 'ef06e630-416c-4ccd-957d-ad087e8e4861', 'aleatoria'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Miriam Reico kano')) LIMIT 1), 'Bradesco', 'Miriam.kanno13@gmail.com', 'email'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Renata Scavuzzi Costa')) LIMIT 1), 'C6', '24904825000107', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Wellington Robson da Silva Paes de Souza')) LIMIT 1), '336', '60344054000104', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Emerson Pena')) LIMIT 1), 'Itau 341', '28757944000127', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Daiane Miranda da Silva')) LIMIT 1), '336- C6 BANK', '44749436000153', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Sergio Glasberg')) LIMIT 1), 'itau', '11991164967', 'cpf'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Paul Christian Carbone')) LIMIT 1), 'Nu bank', '44229215000154', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('EDUARDO LOPES FORTES')) LIMIT 1), 'NU', '18597879000166', 'cnpj'),
('11111111-1111-1111-1111-111111111111', (SELECT id FROM vendors WHERE tenant_id = '11111111-1111-1111-1111-111111111111' AND lower(trim(full_name)) = lower(trim('Rayssa Vitória Cabral de Souza')) LIMIT 1), '336-Banco C6 S.A', '60344054000104', 'cnpj')
ON CONFLICT DO NOTHING;
